### ISSUE TITLE
Idea Blender case study not showing up in navigation

### ISSUE THREAD

**Issue by abandea** [ocupop/arabic-design-tool#1]
Hi @tbeck!

(Marking issues in Github moving forward since I would think that's easiest for you and team to track? But please let me know otherwise!) 

Just noticed the **Idea Blender** case study was missing from the site. It looks like there was a tool created for it already in the Case Studies folder, so I just added the missing content.  
However, the Principal option isn't popping up in the CMS and therefore not showing up in the navigation. It should be under the "Create, Build, and Test" principal. 

Thank you!

**Comment by tbeck** [comment]
@abandea - Thanks for tracking these in Github! 

Commit: 00b81e1

**Comment by abandea** [comment]
Thanks @tbeck! It's showing up in the nav, but when I click the link, I receive a page error

**Comment by tbeck** [comment]
@abandea - I've built a new staging instance and all seems to be fine there. It must be a caching issue, but I'm not sure where. Here is the new URL for testing: https://timely-banjo.cloudvent.net

**Comment by abandea** [comment]
Weird - cleared my cache and still had the problem. But works in the new URL! I'll close this comment. Thank you!
