### ISSUE TITLE
Update data model to include featured video

### ISSUE THREAD

**Issue by tbeck** [ocupop/arabic-design-tool#2]

**Comment by tbeck** [comment]
@abandea - I've added this to the data model. In order to create a responsive iFrame we will need to use the video ID instead of a link or the embed code YouTube provides. 

I've put up the two example videos that you provided:

https://timely-banjo.cloudvent.net/en/tools/feedback-debrief/
https://timely-banjo.cloudvent.net/en/tools/context-tool-problem-definition/

Let me know if there are additional details that we should account for?

Thanks!
T

**Comment by abandea** [comment]
Looks good!

Let's see how it looks like with subtitles. Just received those videos a few minutes ago, so I will upload them tomorrow.

Cheers,
Alex

________________________________

**Comment by tbeck** [comment]
Closing this issue and adding video content.
