### ISSUE TITLE
Reorder/Refactor case-study template

### ISSUE THREAD

**Issue by tbeck** [ocupop/arabic-design-tool#3]
1. Banner Image
2. Title/Summary
3. Featured Video
4. Example
5. Download
6. What/How
7. Testimonial
8. Gallery
9. Related Tools

**Comment by tbeck** [comment]
@abandea - The case study template has been refactored to match the preferred order.

https://timely-banjo.cloudvent.net/

**Comment by abandea** [comment]
Thanks Tom.

**Comment by tbeck** [comment]
Hi @abandea !
I updated the template to remove the featured image/thumbnail.

Thanks,
T

**Comment by abandea** [comment]
Looks great! Thanks
