### ISSUE TITLE
Video module cuts off video when playing

### ISSUE THREAD

**Issue by abandea** [ocupop/arabic-design-tool#6]
Hey @tbeck, 

Minor thing, but the video module on the homepage cuts off the bottom of the video player when you press play. 

<img width="908" alt="Screen Shot 2019-07-17 at 16 40 45" src="https://user-images.githubusercontent.com/42815657/61410103-a86e7600-a8b1-11e9-9ee0-80a2d5d3c482.png">

**Comment by tbeck** [comment]
@abandea - Just pushed a commit that fixes this issue and tested. 

Let me know if you want me to close these issues as I go or leave them for you to review and close?
